theme: jekyll-theme-midnight
title: "Big Idea 2: Guide to adding data related to user "
description: "Joselyn, Ederick, Martin, Akshat, Samit"
gitorg: "https://github.com/B3nto4Lunch/Tri3Project"
google_analytics:
